### ISSUE TITLE
documentation missing and Uncaught Exception 

### ISSUE THREAD

**Issue by mdrijwan** [francismeynard/lambda-multipart-parser#10]
upon deploying my function where i use this package, it throws following error

```undefined	ERROR	Uncaught Exception 	{     "errorType": "Runtime.ImportModuleError",     "errorMessage": "Error: Cannot find module 'lambda-multipart-parser'\nRequire stack:\n- /var/task/src/api/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",     "stack": [         "Runtime.ImportModuleError: Error: Cannot find module 'lambda-multipart-parser'",         "Require stack:",         "- /var/task/src/api/index.js",         "- /var/runtime/UserFunction.js",         "- /var/runtime/index.js",         "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",         "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",         "    at Object.<anonymous> (/var/runtime/index.js:43:30)",         "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",         "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",         "    at Module.load (internal/modules/cjs/loader.js:950:32)",         "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",         "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",         "    at internal/main/run_main_module.js:17:47"     ] } | 2022-01-25T02:50:26.543Z undefined ERROR Uncaught Exception {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'lambda-multipart-parser'\nRequire stack:\n- /var/task/src/api/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'lambda-multipart-parser'","Require stack:","- /var/task/src/api/index.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js"," at _loadUserApp (/var/runtime/UserFunction.js:202:13)"," at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)"," at Object.<anonymous> (/var/runtime/index.js:43:30)"," at Module._compile (internal/modules/cjs/loader.js:1085:14)"," at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)"," at Module.load (internal/modules/cjs/loader.js:950:32)"," at Function.Module._load (internal/modules/cjs/loader.js:790:12)"," at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)"," at internal/main/run_main_module.js:17:47"]}```

and Sample Lambda and API Gateway implementation with Cloudformation can be found in here. this link isn't valid:
https://francismeynard.github.io/aws-upload-document-service

**Comment by willianfalbo** [comment]
any update on this one?
